name: React CI Test

on:
  push:
    branches: [ "shivam" ]
  pull_request:
    branches: [ "shivam" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x, 22.x

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Build Project
        run: npm run build
